### ISSUE TITLE
java.lang.InterruptedException

### ISSUE THREAD

**Issue by xuzhougeng** [ucagenomix/sicelore-2.1#16]
I applied the following version of Java to do the first step of data processing, but encountered the following error report.

```
$ java -version
openjdk version "21.0.1-internal" 2023-10-17
OpenJDK Runtime Environment (build 21.0.1-internal-adhoc.conda.src)
OpenJDK 64-Bit Server VM (build 21.0.1-internal-adhoc.conda.src, mixed mode, sharing)
```

The error message:

```
Nov 06, 2023 5:43:16 PM com.rw.nanoporereadscanner.readerwriter.FastqWriterThreadPool$FastQoneFileThread addChunk
SEVERE: null
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1722)
	at java.base/java.util.concurrent.LinkedBlockingDeque.putLast(LinkedBlockingDeque.java:389)
	at java.base/java.util.concurrent.LinkedBlockingDeque.put(LinkedBlockingDeque.java:642)
	at com.rw.nanoporereadscanner.readerwriter.FastqWriterThreadPool$FastQoneFileThread.addChunk(FastqWriterThreadPool.java:255)
	at com.rw.nanoporereadscanner.readerwriter.FastqWriterThreadPool.addChunkToThread(FastqWriterThreadPool.java:137)
	at com.rw.nanoporereadscanner.WorkerReadscanner$JobDoneCallBack.onSuccess(WorkerReadscanner.java:324)
	at com.rw.nanoporereadscanner.WorkerReadscanner$JobDoneCallBack.onSuccess(WorkerReadscanner.java:313)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

This is my command,

```
java -Xmx40g -jar sicelore-2.1/Jar/NanoporeBC_UMI_finder-2.1.jar  scanfastq -d data2/ -o $PWD/result2 --bcEditDistance 1
```

Could you give me some advice to solve this problem?

**Comment by xuzhougeng** [comment]
It was solved by using JAVA 17
