### ISSUE TITLE
Nextflow pipeline NullPointerException and IllegalStateException

### ISSUE THREAD

**Issue by HenriettaHolze** [ucagenomix/sicelore-2.1#25]
Hi, 

Thanks a lot for making sicelore available as Nextflow pipeline.  
I tried running the test dataset with `nextflow run sicelore-nf/main.nf -profile conda` but got following error: 

```
ERROR ~ Error executing process > 'STEP3_umis'

Caused by:
  Missing output file(s) `passedParsed.bam.genecounts.tsv` expected by process `STEP3_umis`

Command executed:

  java -jar -Xmx12g -XX:ActiveProcessorCount=4 /dawson_genomics/Projects/PRC2_BE_screen/scripts/repositories/sicelore-2.1/Jar/NanoporeBC_UMI_finder-2.1.jar assignumis --inFileNanopore passed.bam -o passedParsed.bam --annotationFile /dawson_genomics/Projects/PRC2_BE_screen/scripts/repositories/sicelore-2.1/Data/gencode.v38.chr12.refFlat

Command exit status:
  0

Command output:

  version=2.1
  build.date=2023-10-16T12:45:44Z
  READING config FILE: config.xml
  Trying current working directory: config.xml
  Not found trying application root:/dawson_genomics/Projects/PRC2_BE_screen/scripts/repositories/sicelore-2.1/Jar/config.xml
  O.K. Found and using /dawson_genomics/Projects/PRC2_BE_screen/scripts/repositories/sicelore-2.1/Jar/config.xml
  Log written to passedParsed.bam.log
  READING umi clustering edit distances FILE: umiClusteringEditDistances.xml
  Trying current working directory: umiClusteringEditDistances.xml
  Not found trying application root:/dawson_genomics/Projects/PRC2_BE_screen/scripts/repositories/sicelore-2.1/Jar/umiClusteringEditDistances.xml
  O.K. Found and using /dawson_genomics/Projects/PRC2_BE_screen/scripts/repositories/sicelore-2.1/Jar/umiClusteringEditDistances.xml

Command error:
  WARNING       2024-09-22 10:17:52     SamFiles        The index file /dawson_genomics/Projects/PRC2_BE_screen/scripts/repositories/sicelore-2.1/work/60/f6afb510c96b865d1124aed9e78728/passed.bam.bai was found by resolving the canonical path of a symlink: passed.bam -> /dawson_genomics/Projects/PRC2_BE_screen/scripts/repositories/sicelore-2.1/work/60/f6afb510c96b865d1124aed9e78728/passed.bam
  Exception in thread "Thread-1" java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
        at com.google.common.base.Absent.get(Absent.java:44)
        at com.rw.umifinder.bamreaderswriters.ReadGrouper.lambda$groupSams$0(ReadGrouper.java:121)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at com.rw.umifinder.bamreaderswriters.ReadGrouper.groupSams(ReadGrouper.java:123)
        at com.rw.umifinder.bamreaderswriters.BamReader.run(BamReader.java:145)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Exception in thread "Thread-0" java.lang.NullPointerException: Cannot invoke "com.rw.umifinder.bamreaderswriters.BamReader$NanoporeReadChunk.size()" because "nanoporeReads" is null
        at com.rw.umifinder.OneBatchExecutor.<init>(OneBatchExecutor.java:56)
        at com.rw.umifinder.UmiFinderWorker.run(UmiFinderWorker.java:131)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

I'm running nextflow v23.04.1.

**Comment by HenriettaHolze** [comment]
I realized I had minimap2 v2.9 in my PATH that did not recognize the sam-hit-only and junc-bed parameters and the resulting BAM file only had unmapped reads.  
Using the conda environment I can run the test dataset without problems now.
