### ISSUE TITLE
java.io.FileNotFoundException ComputeConsensus results in "null" sequence

### ISSUE THREAD

**Issue by HenriettaHolze** [ucagenomix/sicelore-2.1#28]
Hi, 

I'm running the nextflow pipeline and observed that I get 1,328,757 UMI after step 4a and 931,350 UMI after step 4b. 

I figures that I get the same error as in https://github.com/ucagenomix/sicelore/issues/39 but I could not find a fix to the problem. 
Transcripts with multiple reads have "null" sequence and quality after `ComputeConsensus`.

The run command in `.command.sh` is 

```
java -jar -Xmx64g /dawson_genomics/Projects/PRC2_BE_screen/scripts/repositories/sicelore-2.1/Jar/Sicelore-2.1.jar ComputeConsensus -T 10 -I chromosome.bam -O chr.fq -CELLTAG BC -UMITAG U8 -GENETAG GE -TSOENDTAG TE -POLYASTARTTAG PS -CDNATAG CS -USTAG US -RNTAG RN -MAPQV0 false -TMPDIR /scratch/teams/dawson_genomics/Projects/PRC2_BE_screen/results/MF03_nanopore/sicelore/output/tmp -VALIDATION_STRINGENCY SILENT -MAXREADS 20 -MINPS 3 -MAXPS 20 -DEBUG false
```

`chr.fq`

```
@CTCGTACTCTCCAACC-CATAGCTTTC-4
null
+
null
```

`.command.err`

```
java.io.FileNotFoundException: /scratch/teams/dawson_genomics/Projects/PRC2_BE_screen/results/MF03_nanopore/sicelore/output/tmp/CTCGTACTCTCCAACC-CATAGCTTTC-4_reads.fa (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:123)
        at org.ipmc.sicelore.utils.Consensus.call(Consensus.java:209)
        at org.ipmc.sicelore.utils.Consensus.call(Consensus.java:14)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Sequences from CTCGTACTCTCCAACC-CATAGCTTTC-4 in `chromosome.bam`

```
5bb334b7-f4d8-47f8-be0c-7d482e4d88f6_FWD_AE=97_bc=CTCGTACTCTCCAACC_ed=0_ed_sec=2147483647_bcStart=98_bcEnd=113_rk=0_X=TCTCTCGTACTCTCCAACCCATAGCTTTCTTTCTTATATGGG_Q=26.3_2rwoj   16      chr5    181238219       60      19S21M827N111M309N96M1909N65M1D82M534N43M2I129M1346N154M137S    *       0       0       CGTATTGCTCAGTGTTTGTCCATAACATGGCCTGGCCATCCTTGCCTCCAGAAGCACAGAGGGATCCATCTGGAGAGACAGTCACCGTGTTCAGATAGCCTGTGTGGCCAATGTGGTTGGTCTTCAGCTTGCAGTTAGCCAGGTTCCATACCTTGACCAGCTTGTCCCAGCCACAGGAGACGATGATAGGGTTGCTGCTGTTGGGCGAGAAGCGGACACAAGACACCCACTCTGAGTGGCTCTCATCCTGGACAGTGTATTTGCACACACCCAGGGTATTCCATAGCTTGATGGTTTTATCTCTATATCTAGTACAATCTGCCGGTTGTCACAGGAGAAGGCCACACTCAGCACATCCTTGGTATGGCCCACAAATCGCCTCGTGGTGGTGCCCGTTGTGAGATCCCAGAGGCGCAGGGTTCCATCCCAGGAGCCTGATAGAGGGCAAACTGGCCATCTGAGGAGATAACCACATCACTAACAAAGCGGGAGTGACCCCGCAGAGCACGCTGTGGAATTCCATAGTTGGTCTCATCCCTGGTCAGTTTCCACATGATGATGGTCTTATCTCGAGAGGCGGAGAGGATCATGTCCGGGAACTGCGGGGTAGTAGCGATCTGGGTTACCCAGCCGTTGTGGCCCTTGAGGGTGCCACGAAGGGTCATCTGCTCAGTCATGGCGGCGGCGAGAGCGTGTGTCGCTGCAGCGACGAGGATGGCACTACCCATATAAGAAAGAAAGCTATGGGTTGGAGAGTACGAGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATTAGCAATACGTAACTGAACGAGTAGGTTACACATAAACAT     '*,...3346@A;::::?@???>@?@A???>>>>>>=>>>@=<;;;=>@@?@>>?AA=<<;;<===>=9::;;>>????@@:9999?FEBA@??><=>>?CC@?>>;<<:::9:===<=>>?CAAAAABCB@??>>@?>==;<===?>>?@A>>===@@ACBBBAAAAAABB??>>;9899<@?><;<<=>AB??AA@?:4200/*)**....//8:<<@@@@<;::;>?A@BB@?>===>>>:994338>@@>?@AAEEFDEEDC?====>==>??>>??A@@@BBEDCCBBDGEAAA<989:<;922236=?<<<>76666;=;;*))));;;<;>=:;?@CBA@A@@ADBABA@A@>?@>@@>>?@@DB=88888<<==?B@@A?>;;:;;?@A=<===>>===>,,,,,;6..('((+,.....<?@1..))((+0++6:9?ABBCCBDEDEEEAA211=?A??AAEEFHH=99930/,**))+,+....:-,,,105=C>====CBBCCCDEDAABC:8888=<<==<;9;9212234?CEDDCDDCBBAAB@@??>?>>?>;;;))+999:9:::9;;<==<=;9998=>><=:998:<==??===>>AAA@==<<<;9<<6665566667>>@?A@@?>>>==;67333A5=BBBADBA<<<<=ACDCA@?>===<===><<<>;;<<:><==>>?>>====>?@@A@>>=>=>???ABC=54=9,,1;9<=?@@>>>>>@;:A@@?>==;<::;;3438<;;877769::;<<<=@@6;<9:>>>?@AB@?>>>?=;8855577;;>>>@??>88<933220000135323.,++*)(''&%$$$$$$###     B1:i:0  U1:Z:0  s1:i:622        B2:Z:2147483647 U2:Z:5  s2:i:157        U7:Z:CATAGCTTTC U8:Z:CATAGCTTTC BB:Z:98 BC:Z:CTCGTACTCTCCAACC   UC:Z:   AE:i:97 BE:Z:113        GE:Z:RACK1      BF:Z:113        XF:Z:CODING     BH:Z:0  NM:i:9  AS:i:601        GS:Z:-  QS:Z:###$$$$$$%&''()*++,.323531000022339<88>??@>>>;;7755588;=?>>>?@BA@?>>>:9<;6@@=<<<;::967778;;<8343;;::<;==>?@@A:;@>>>>>@@?=<9;1,,9=45=CBA???>=>=>>@A@@?>====>>?>>==<>:<<;;><<<>===<===>?@ACDCA=<<<<ABDABBB=5A33376;==>>>?@@A?@>>7666655666<<9;<<<==@AAA>>===??==<:899:=<>>=8999;=<==<;;9:::9:999+));;;>?>>?>??@@BAABBCDDCDDEC?4322129;9;<==<<=8888:CBAADEDCCCBBC====>C=501,,,-:....+,+))**,/03999=HHFEEAA??A?=112AAEEEDEDBCCBBA?9:6++0+(())..1@?<.....,+(('(..6;,,,,,>===>>===<=A@?;;:;;>?A@@B?==<<88888=BD@@?>>@@>@?>@A@ABABDA@@A@ABC@?;:=>;<;;;))))*;;=;66667><<<?=632229;<:989<AAAEGDBBCCDEBB@@@A??>>??>==>====?CDEEDFEEAA@?>@@>833499:>>>===>?@BB@A?>;::;<@@@@<<:8//....**)*/0024:?@AA??BA>=<<;<>?@<9989;>>??BBAAAAAABBBCA@@===>>A@?>>?===<;==>?@>>??@BCBAAAAAC?>>=<===:9:::<<;>>?@CC?>>=<>??@ABEF?9999:@@????>>;;::9=>===<;;<<=AA?>>@?@@>=;;;<=@>>>=>>>>>>???A@?@>???@?::::;A@6433...,*'        US:Z:ATGTTTATGTGTAACCTACTCGTTCAGTTACGTATTGCTAATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCTCTCGTACTCTCCAACCCATAGCTTTCTTTCTTATATGGGTAGTGCCATCCTCGTCGCTGCAGCGACACACGCTCTCGCCGCCGCCATGACTGAGCAGATGACCCTTCGTGGCACCCTCAAGGGCCACAACGGCTGGGTAACCCAGATCGCTACTACCCCGCAGTTCCCGGACATGATCCTCTCCGCCTCTCGAGATAAGACCATCATCATGTGGAAACTGACCAGGGATGAGACCAACTATGGAATTCCACAGCGTGCTCTGCGGGGTCACTCCCGCTTTGTTAGTGATGTGGTTATCTCCTCAGATGGCCAGTTTGCCCTCTATCAGGCTCCTGGGATGGAACCCTGCGCCTCTGGGATCTCACAACGGGCACCACCACGAGGCGATTTGTGGGCCATACCAAGGATGTGCTGAGTGTGGCCTTCTCCTGTGACAACCGGCAGATTGTACTAGATATAGAGATAAAACCATCAAGCTATGGAATACCCTGGGTGTGTGCAAATACACTGTCCAGGATGAGAGCCACTCAGAGTGGGTGTCTTGTGTCCGCTTCTCGCCCAACAGCAGCAACCCTATCATCGTCTCCTGTGGCTGGGACAAGCTGGTCAAGGTATGGAACCTGGCTAACTGCAAGCTGAAGACCAACCACATTGGCCACACAGGCTATCTGAACACGGTGACTGTCTCTCCAGATGGATCCCTCTGTGCTTCTGGAGGCAAGGATGGCCAGGCCATGTTATGGACAAACACTGAGCAATACG        BU:Z:CTCGTACTCTCCAACC   BV:Z:98 BW:i:0  BX:Z:N.A.       SX:Z:4661299    BZ:Z:CTCGTACTCTCCAACC   de:f:0.0114     rl:i:0  cm:i:193        nn:i:0  tp:A:P  ms:i:676        ts:A:+
947dbf4d-e9db-4590-aa2f-2879614e29ee_REV_AE=39_bc=CTCGTACTCTCCAACC_ed=0_ed_sec=2147483647_bcStart=39_bcEnd=54_rk=0_X=TCCTCGTACTCTCCAACCCATAGCTTTCTTTCTTATATGGGT_Q=24.2_3wdxk    16      chr5    181238219       60      47S21M827N111M309N96M1909N148M534N10M1D161M1346N154M78S *       0       0       ATGTTGTGTGTCTTACTTCGTTCAGTTACGTATTGCTTAGTGTTTGTCCATAACATGGCCTGGCCATCCTTGCCTCCAGAAGCACAGAGGGATCCATCTGGAGAGACAGTCACCGTGTTCAGATAGCCTGTGTGGCCAATGTGGTTGGTCTTCAGCTTGCAGTTAGCCAGGTTCCATACCTTGACCAGCTTGTCCCAGCCACAGGAGACGATGATAGGGTTGCTGCTGTTGGGCGAGAAGCGGACACAAGACACCCACTCTGAGTGGCTCTCATCCTGGACAGTGTATTTGCACACACCCAGGGTATTCCATAGCTTGATGGTTTTATCTCGAGATCCAGAGACAATCTGCCGGTTGTCAGAGGAGAAGGCCACACTCAGCACATCCTTGGTATGGCCCACAAATCGCCTCGTGGTGGTGCCCGTTGTGAGATCCAGAGGCGCAGGGTTCCATCCCAGGAGCCTGAGAGGGCAAACTGGCCATCTGAGGAGATAACCACATCACTAACAAAGTGGGAGTGACCCCGCAGAGCACGCTGTGGAATTCCATAGTTGGTCTCATCCCTGGTCAGTTTCCACATGATGATGGTCTTATCTCGAGAGGCGGAGAGGATCATGTCCGGGAACTGCGGGGTAGTAGCGATCTGGGTTACCCAGCCGTTGTGGCCCTTGAGGGTGCCACGAAGGGTCATCTGCTCAGTCATGGCGGCGGCGAGAGCGTGTGTCGCTGCAGCGACGAGGATGGCACTACCCATATAAGAAAGAAAGCTATGGGTTGGAGAGTACGAGGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCT      %&%((('&&$$$$$&),,+,/568???><::9+)))),--..>@B>>>>>AAABBC311119@?@66558,+****-)*?@?ABBBAA=;::;==BBBDDBBBBAABCCCCCB?===>@CCCBBA@@>>??@AABCB43334EB@@A@@???@BDDCCDDDCBA><;<<>>?>==>>@A@@ABBCDDA?>>>@A?????DDFEGAA@@>::::<BA?;:::;?BDBBDBCB=<654459;;44445BDC@@@@@???>?BBB@@@?=<<;<=??>====>???@A@ACBCCBBCBDFDC@==:76689;<<?C??>>?ABB????AFJDD43333??A44@@@@>>@==??88777;?>??B><<=>@@?===>>CFB?3////CA@<<>>>BA@>>;;;<<?@A?;;:::;;;;>AAAB??98888>CDDCDC9+,CB@<8831122:::99?@?>>?@@>==:777E?====?@???=>>?=??=:;99:@>>>>>@@ABCB@@@AACB?=><;<<=?AAA?:7778;AAA>;;;;>AAABCCECA@8887211125<>AA@@:55+++++47=::BE====GEB>>=<=?@BB?0/..;<:::;;??>>??BBAA@=::::<CCC>98878;<===<<=>?@CA???>?@@ABA?>>>>@BBA@?>A?@?=<;;<=???AA@@?==>?ACCABBBBCCCCBC?>><;;;;;;<<=====>@=9998:<:96665688:==>@@?>>;;;;<>@81//0?88AC@@>======>=====<<;:,***---0278<@::999::<<=@><4?95832/+)))**(      B1:i:0  U1:Z:0  s1:i:638        B2:Z:2147483647 U2:Z:5  s2:i:173        U7:Z:CATAGCTTTC U8:Z:CATAGCTTTC BB:Z:39 BC:Z:CTCGTACTCTCCAACC   UC:Z:   AE:i:39 BE:Z:54 GE:Z:RACK1      RE:Z:   BF:Z:54 XF:Z:CODING     BH:Z:0  NM:i:1  AS:i:623        GS:Z:-  QS:Z:(**)))+/23859?4<>@=<<::999::@<8720---***,:;<<=====>======>@@CA88?0//18@><;;;;>>?@@>==:88656669:<:8999=@>=====<<;;;;;;<>>?CBCCCCBBBBACCA?>==?@@AA???=<;;<=?@?A>?@ABB@>>>>?ABA@@?>???AC@?>=<<===<;87889>CCC<::::=@AABB??>>??;;:::<;../0?BB@?=<=>>BEG====EB::=74+++++55:@@AA><5211127888@ACECCBAAA>;;;;>AAA;8777:?AAA?=<<;<>=?BCAA@@@BCBA@@>>>>>@:99;:=??=?>>=???@?====?E777:==>@@?>>?@?99:::2211388<@BC,+9CDCDDC>88889??BAAA>;;;;:::;;?A@?<<;;;>>@AB>>><<@AC////3?BFC>>===?@@>=<<>B??>?;77788??==@>>@@@@44A??33334DDJFA????BBA?>>??C?<<;98667:==@CDFDBCBBCCBCA@A@???>====>??=<;<<=?@@@BBB?>???@@@@@CDB54444;;954456<=BCBDBBDB?;:::;?AB<::::>@@AAGEFDD?????A@>>>?ADDCBBA@@A@>>==>?>><<;<>ABCDDDCCDDB@???@@A@@BE43334BCBAA@??>>@@ABBCCC@>===?BCCCCCBAABBBBDDBBB==;::;=AABBBA?@?*)-****+,85566@?@911113CBBAAA>>>>>B@>..--,))))+9::<>???865/,+,,)&$$$$$&&'(((%&% US:Z:AGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCCTCGTACTCTCCAACCCATAGCTTTCTTTCTTATATGGGTAGTGCCATCCTCGTCGCTGCAGCGACACACGCTCTCGCCGCCGCCATGACTGAGCAGATGACCCTTCGTGGCACCCTCAAGGGCCACAACGGCTGGGTAACCCAGATCGCTACTACCCCGCAGTTCCCGGACATGATCCTCTCCGCCTCTCGAGATAAGACCATCATCATGTGGAAACTGACCAGGGATGAGACCAACTATGGAATTCCACAGCGTGCTCTGCGGGGTCACTCCCACTTTGTTAGTGATGTGGTTATCTCCTCAGATGGCCAGTTTGCCCTCTCAGGCTCCTGGGATGGAACCCTGCGCCTCTGGATCTCACAACGGGCACCACCACGAGGCGATTTGTGGGCCATACCAAGGATGTGCTGAGTGTGGCCTTCTCCTCTGACAACCGGCAGATTGTCTCTGGATCTCGAGATAAAACCATCAAGCTATGGAATACCCTGGGTGTGTGCAAATACACTGTCCAGGATGAGAGCCACTCAGAGTGGGTGTCTTGTGTCCGCTTCTCGCCCAACAGCAGCAACCCTATCATCGTCTCCTGTGGCTGGGACAAGCTGGTCAAGGTATGGAACCTGGCTAACTGCAAGCTGAAGACCAACCACATTGGCCACACAGGCTATCTGAACACGGTGACTGTCTCTCCAGATGGATCCCTCTGTGCTTCTGGAGGCAAGGATGGCCAGGCCATGTTATGGACAAACACTAAGCAATACGTAACTGAACGAAGTAAGACACACAACAT BU:Z:CTCGTACTCTCCAACC   BV:Z:39 BW:i:0  BX:Z:N.A.       SX:Z:6549896    BZ:Z:CTCGTACTCTCCAACC   de:f:0.0014     rl:i:0  cm:i:218        nn:i:0  tp:A:P  ms:i:698        ts:A:+
f171f468-98e1-4715-926f-bec2f4625f75_FWD_AE=90_bc=CTCGTACTCTCCAACC_ed=0_ed_sec=2147483647_bcStart=91_bcEnd=106_rk=0_X=TCTCTCGTACTCTCCAACCCATAGCTTTCTTTCTTATATGGG_Q=30.4_nva9    16      chr5    181238219       60      20S21M827N36M1D3M1D53M1I17M309N96M1909N148M534N172M1346N154M130S        *       0       0       ATGTATTGCTCAGTGTTTGTCCATAACATGGCCTGGCCATCCTTGCCTCCAGAAGCACAGAGGGATCCATCTGGAGAATACCACTGTGTTCAGATAGCCTGTGTGGCCAATGTGGTTGGTCTTCAGCTTGCAGCTCAGCCAGGTTCCATACCTTGACCAGCTTGTCCCAGCCACAGGAGACGATGATAGGGTTGCTGCTGTTGGGCGAGAAGCGGACACAAGACACCCACTCTGAGTGGCTCTCATCCTGGACAGTGTATTTGCACACACCCAGGGTATTCCATAGCTTGATGGTTTTATCTCGAGATCCAGAGACAATCTGCCGGTTGTCAGAGGAGAAGGCCACACTCAGCACATCCTTGGTATGGCCCACAAATCGCCTCGTGGTGGTGCCCGTTGTGAGATCCCAGAGGCGCAGGGTTCCATCCCAGGAGCCTGAGAGGGCAAACTGGCCATCTGAGGAGATAACCACATCACTAACAAAGTGGGAGTGACCCCGCAGAGCACGCTGTGGAATTCCATAGTTGGTCTCATCCCTGGTCAGTTTCCACATGATGATGGTCTTATCTCGAGAGGCGGAGAGGATCATGTCCGGGAACTGCGGGGTAGTAGCGATCTGGGTTACCCAGCCGTTGTGGCCCTTGAGGGTGCCACGAGGGGTCATCTGCTCAGTCATGGCGGCGGCGAGAGCGTGCGTCGCTGCAGCGACGAGGATGGCACTACCCATATAAGAAAGAAAGCTATGGGTTGGAGAGTACGAGAGATCGGAAGAGCGTCGTGTAGGGAAAGAAGTGTAGATCTCGGTGTACTGTGGATCATTACAAGTACGTAACTGAACGAGTAGACGACAT     )+))))*0-,-;;657732''&(((24??ACCAAAABCCCCEDDCBCDBFDDDCCFFECAAAAABC@?>:0-.(&&*%%%%&**+.,,,-0<<?>@A@@BCBBBBACDEEEFA@;;78889<++)))))())**++=BBADCBBA??@A=====@???BBEDEDDCCDCCDCA?>>==<<=>AA@???@ABCGFEFDCCAA<:99:<B<66667DFFB@@??@@@@?@ABABCBA???>@BCCAAB@AABABCBBBCBCBCCCCCEBAB@?>==>???@@@BABBDCHECCDEFGGAA87777=AABA????A?@???A;9999=BCCDFFDB@BB?><<=>@BCBAAABBBDCAAAAA?<=<=?CBCCD?A@@:::::>>??BFDDDA@=<<==@AAAA@@>>??ACB<::::<??@@CCCBAA@A???@@=<764577/357BFFDABBADEEGCBBAABDBBBBBCDDCCBCAABD66:DB=6::55668<:;;;>CCC?====?B@=,+++&'')2;;;98664466680000.2222FECBAAACDDCCBCA@?@3..3@<<;;;33214::<?>>==>@@@A>////<=>BA@@@28?>===<<=>>:987686889@??<..-,)&&&&1:>AABA=<<<)(((',))-)12698;<<<>:::JFGEC@A@??<<<;;==>=>22222?>>@??@??>>?>>?@ACEAA??>>>?@DDDEDDFFDEGHED@?????????@@@ABAB??222;:;770//./,,001568:--)*/1158889++***+,++++*%$$$%&''''((+*)'''(((())**,,//0012+))+'%$$$$%&%$#     B1:i:0  U1:Z:0  s1:i:630        B2:Z:2147483647 U2:Z:5  s2:i:165        U7:Z:CATAGCTTTC U8:Z:CATAGCTTTC BB:Z:91 BC:Z:CTCGTACTCTCCAACC   UC:Z:   AE:i:90 BE:Z:106        GE:Z:RACK1      BF:Z:106        XF:Z:CODING     BH:Z:0  NM:i:9  AS:i:598        GS:Z:-  QS:Z:#$%&%$$$$%'+))+2100//,,**))((((''')*+((''''&%$$$%*++++,+***++9888511/*)--:865100,,/.//077;:;222??BABA@@@?????????@DEHGEDFFDDEDDD@?>>>??AAECA@?>>?>>??@??@>>?22222>=>==;;<<<??@A@CEGFJ:::><<<;89621)-)),'((()<<<=ABAA>:1&&&&),-..<??@988686789:>>=<<===>?82@@@AB>=<////>A@@@>==>>?<::41233;;;<<@3..3@?@ACBCCDDCAAABCEF2222.00008666446689;;;2)''&+++,=@B?====?CCC>;;;:<86655::6=BD:66DBAACBCCDDCBBBBBDBAABBCGEEDABBADFFB753/775467<=@@???A@AABCCC@@??<::::<BCA??>>@@AAAA@==<<=@ADDDFB??>>:::::@@A?DCCBC?=<=<?AAAAACDBBBAAABCB@>=<<>?BB@BDFFDCCB=9999;A???@?A????ABAA=77778AAGGFEDCCEHCDBBAB@@@???>==>?@BABECCCCCBCBCBBBCBABAA@BAACCB@>???ABCBABA@?@@@@??@@BFFD76666<B<:99:<AACCDFEFGCBA@???@AA>=<<==>>?ACDCCDCCDDEDEBB???@=====A@??ABBCDABB=++**))()))))++<98887;;@AFEEEDCABBBBCB@@A@>?<<0-,,,.+**&%%%%*&&(.-0:>?@CBAAAAACEFFCCDDDFBDCBCDDECCCCBAAAACCA??42(((&''237756;;-,-0*))))+)        US:Z:ATGTCGTCTACTCGTTCAGTTACGTACTTGTAATGATCCACAGTACACCGAGATCTACACTTCTTTCCCTACACGACGCTCTTCCGATCTCTCGTACTCTCCAACCCATAGCTTTCTTTCTTATATGGGTAGTGCCATCCTCGTCGCTGCAGCGACGCACGCTCTCGCCGCCGCCATGACTGAGCAGATGACCCCTCGTGGCACCCTCAAGGGCCACAACGGCTGGGTAACCCAGATCGCTACTACCCCGCAGTTCCCGGACATGATCCTCTCCGCCTCTCGAGATAAGACCATCATCATGTGGAAACTGACCAGGGATGAGACCAACTATGGAATTCCACAGCGTGCTCTGCGGGGTCACTCCCACTTTGTTAGTGATGTGGTTATCTCCTCAGATGGCCAGTTTGCCCTCTCAGGCTCCTGGGATGGAACCCTGCGCCTCTGGGATCTCACAACGGGCACCACCACGAGGCGATTTGTGGGCCATACCAAGGATGTGCTGAGTGTGGCCTTCTCCTCTGACAACCGGCAGATTGTCTCTGGATCTCGAGATAAAACCATCAAGCTATGGAATACCCTGGGTGTGTGCAAATACACTGTCCAGGATGAGAGCCACTCAGAGTGGGTGTCTTGTGTCCGCTTCTCGCCCAACAGCAGCAACCCTATCATCGTCTCCTGTGGCTGGGACAAGCTGGTCAAGGTATGGAACCTGGCTGAGCTGCAAGCTGAAGACCAACCACATTGGCCACACAGGCTATCTGAACACAGTGGTATTCTCCAGATGGATCCCTCTGTGCTTCTGGAGGCAAGGATGGCCAGGCCATGTTATGGACAAACACTGAGCAATACAT        BU:Z:CTCGTACTCTCCAACC   BV:Z:91 BW:i:0  BX:Z:N.A.       SX:Z:1113633    BZ:Z:CTCGTACTCTCCAACC   de:f:0.0128     rl:i:0  cm:i:197        nn:i:0  tp:A:P  ms:i:673        ts:A:+
9c7fc715-9720-41a6-94c0-cc765a776747_REV_AE=67_bc=CTCGTACTCTCCAACC_ed=0_ed_sec=2147483647_bcStart=68_bcEnd=83_rk=0_X=TCTCTCGTACTCTCCAACCCATAGCTTTCTTCTATATGGGTA_Q=16.4_20bkh    16      chr5    181239066       60      62S19M1I93M309N96M1909N25M1D29M1D92M534N5M1I90M1D42M2I1M1D32M1346N23M1I27M5D19M1D54M1I25M105S   *       0       0       GTTATGTTAACCTACTGATTCAGCGTATTGCTCAGTGTTTGTCCATAACATCGTCTGGCCATCCTTGCCTCCAGAAGCACAGGAGGGATCCATCTGGAGAGACAGTCACCGTGTTCAGATAGCCTGTGTGGCCAATGTGGTTGGTCTTCAGCTTGCCATTAGCCAGGTTCCATACCTTGACCAGCTTGTCCCAGCCACAGGAGACGATGATAGGGTTGCTGCTGTTGGGCGAGAAGCGGACACAAGACACCCACTCTGAGTGGCTCTCATCCTGGACAGTGTATTTGCACACACCCGGGTATTCCATAGCTTGATGGTTTTATCTGAGATCCAGAGACAATCTGCCGGTTGTCAGAGGAGAAGGCCACACTCAGCACATCCTTGGTATGGCCCACAAATCGCCTCGTGGTGGTGCCCGTTGTAGAGATCCCAGAGGCGCAGGGTTCCATCCCAGGAGCCTGAGAGGCCGAACTGGCCATCTGAGGAGATCACCACATCACTAACAAAGTGGGATGGCCCCGCAGAGCACGCTGTGGAAACCCATAGTTGGTCTCAAGTCCTGGTCATTTTCCACATGATGATGGTCTTATCTCGAGAGGCGGAGAGGATCATGTTCCGGGAACTGCGGGGTAGTAGCGATCAACCCAGCCGTTGTGACCCTGAGGGTGCCACGAAGGGTCATCTGCTCAGTCATGGCGGCGGCGAGAGCGTGTGTTCGCTGCGGCGACGAGGATGGCACTACCCATATAGAAGAAAGCTATGGGTTGGAGAGTACGAGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTGAGTCGGTGGTCGCCGTATCATTAGCAATACGTA   %&))())(%$$##$$$$$%%%&'&())2:>??65555@E200//,../...)*'&&'+69>?=====<<=223:::;>=</-,(&&)('(('(++++,CDCCCCAAB@?;;;99:55CDGEBA@A@ADDBA@@@ADGFHDCCDAB@AA++++++*****+'''&%%.))+2*+@??>=<<=@AAAA;88665..AAAC66.()'.+++,,2/,,,-78;<??AA=3((755888:=:1111299:<=;<<BC8BABA@:888;>>>>?ABBACA@@@@@@A@?A@AADCC@@@@@>55552211119=:9:>>@BB????@CDDB@@??@?@CBB@@?@ACBDCC=::::=H6655577:54445;?A@AA@;;9:;88/.//...8;=====?@@@42....<<<<<=?BB@A@=;999;=/...2>;:811<BB?99999??@>>=<>@?>?DB?>>8/-,-.1(('&&&')*+/00...../,,''&&''%&&'('(),,-)'()*411/+)(((''''))),/02)(((('%&&)%%$%&''''%&&&'*10(((()**+,,+())+,,,3@?AAB@?<;;:??>?AB22223<>??<;;::=:8&%%%%&%%&(*39A?>=<;;<<;<<654,))%%%&**,,,+*)**++(')(''*+7:6:>@??@@AAACA?=>332233---03:;=A@@A??><;;8976677;;7-,+**)&&''&'&&&&'+'''&'(((/235552222**1/++88999::<4100/2+++***24:?><==>>@=<9999:=====858:/..-/1++**'&%%'))))*))899:=>?A@A>==;931)   B1:i:0  s1:i:530        B2:Z:2147483647 s2:i:128        U7:Z:CATAGCTTTC U8:Z:CATAGCTTTC BB:Z:68 BC:Z:CTCGTACTCTCCAACC   AE:i:67 BE:Z:83 GE:Z:RACK1      RE:Z:   BF:Z:83 XF:Z:CODING     BH:Z:0  NM:i:28 AS:i:537        GS:Z:-  QS:Z:)139;==>A@A?>=:998))*))))'%%&'**++1/-../:858=====:9999<=@>>==<>?:42***+++2/0014<::99988++/1**222255532/((('&'''+'&&&&'&''&&)**+,-7;;7766798;;<>??A@@A=;:30---332233>=?ACAAA@@??@>:6:7+*''()'(++**)*+,,,**&%%%)),456<<;<<;;<=>?A93*(&%%&%%%%&8:=::;;<??><32222BA?>??:;;<?@BAA?@3,,,+))(+,,+**)((((01*'&&&%''''&%$%%)&&%'(((()20/,)))''''((()+/114*)(')-,,)('('&&%''&&'',,/.....00/+*)'&&&'((1.-,-/8>>?BD?>?@><=>>@??99999?BB<118:;>2.../=;999;=@A@BB?=<<<<<....24@@@?=====;8...//./88;:9;;@AA@A?;54445:7755566H=::::=CCDBCA@?@@BBC@?@??@@BDDC@????BB@>>:9:=91111225555>@@@@@CCDAA@A?@A@@@@@@ACABBA?>>>>;888:@ABAB8CB<<;=<:9921111:=:888557((3=AA??<;87-,,,/2,,+++.')(.66CAAA..56688;AAAA@=<<=>??@+*2+)).%%&'''+*****++++++AA@BADCCDHFGDA@@@ABDDA@A@ABEGDC55:99;;;?@BAACCCCDC,++++('(('()&&(,-/<=>;:::322=<<=====?>96+'&&'*).../..,//002E@55556??>:2))(&'&%%%$$$$$##$$%())())&%      US:Z:TACGTATTGCTAATGATACGGCGACCACCGACTCACACTCTTTCCCTACACGACGCTCTTCCGATCTCTCGTACTCTCCAACCCATAGCTTTCTTCTATATGGGTAGTGCCATCCTCGTCGCCGCAGCGAACACACGCTCTCGCCGCCGCCATGACTGAGCAGATGACCCTTCGTGGCACCCTCAGGGTCACAACGGCTGGGTTGATCGCTACTACCCCGCAGTTCCCGGAACATGATCCTCTCCGCCTCTCGAGATAAGACCATCATCATGTGGAAAATGACCAGGACTTGAGACCAACTATGGGTTTCCACAGCGTGCTCTGCGGGGCCATCCCACTTTGTTAGTGATGTGGTGATCTCCTCAGATGGCCAGTTCGGCCTCTCAGGCTCCTGGGATGGAACCCTGCGCCTCTGGGATCTCTACAACGGGCACCACCACGAGGCGATTTGTGGGCCATACCAAGGATGTGCTGAGTGTGGCCTTCTCCTCTGACAACCGGCAGATTGTCTCTGGATCTCAGATAAAACCATCAAGCTATGGAATACCCGGGTGTGTGCAAATACACTGTCCAGGATGAGAGCCACTCAGAGTGGGTGTCTTGTGTCCGCTTCTCGCCCAACAGCAGCAACCCTATCATCGTCTCCTGTGGCTGGGACAAGCTGGTCAAGGTATGGAACCTGGCTAATGGCAAGCTGAAGACCAACCACATTGGCCACACAGGCTATCTGAACACGGTGACTGTCTCTCCAGATGGATCCCTCCTGTGCTTCTGGAGGCAAGGATGGCCAGACGATGTTATGGACAAACACTGAGCAATACGCTGAATCAGTAGGTTAACATAAC      BU:Z:CTCGTACTCTCCAACC   BV:Z:68 BW:i:0  BX:Z:N.A.       SX:Z:3374225    BZ:Z:CTCGTACTCTCCAACC   UZ:Z:   de:f:0.0337     rl:i:0  cm:i:136        nn:i:0  tp:A:P  ms:i:601        ts:A:+
```

Any help would be much appreciated!

Best, 
Henrietta

**Comment by HenriettaHolze** [comment]
This error was caused by tmpdir not existing. The default value for tmpdir is relative to the outdir. If the outdir is relative, the tmpdir will be placed inside the process work directory. If the outdir is set to an absolute path, the pipeline seems not capable to find the tmpdir if left at the default value.  
I added a suggestion how to fix this to my pull request.
