### ISSUE TITLE
NanoporeBC_UMI_Finder processes incorrect number of reads

### ISSUE THREAD

**Issue by jindalk** [ucagenomix/sicelore-2.1#9]
Hi,
I am processing a PromethION run with 191mil reads. The first pass of the pipeline processes close to 160mil reads (not a big drop). However, the second pass processes only 4mil reads. I am not sure if this is an issue with my data or if I am running the script incorrectly. This is my first time running any kind of long reads analysis, any help would be greatly appreciated! Here is the relevant portion of my log file:

```
First pass - Defining used barcodes
Pass 1 - defining used barcodes
  94% [==============================================================================================>      ] 38728/41202 files, 154910507 reads, ETA: 00:08:14
All threads submitted - waiting for threads to terminate
Finished parsing - calculating barcodes and stats
stopping cell barcode analyzer - waiting for termination reads chunks pending: 0
Finalizing list of used barcodes
	Testing barcode list for colissions. List size: 1120441 Reads used: 81865783
	Testing barcode list for colissions. List size after filter: 349172 Reads used: 81094514
	 eliminating colliding BCs
	Testing barcode list for colissions. List size after collission merge: 86002 Reads used: 79638667
done Finalizing barcode list
Total reads: 155002507
Barcode extracted: 107287453
Barcode in whitelist: 81865783
finished generating barcode list

Pass 2 - stranding reads, assigning barcodes
   2% [==>                                                                                                  ]   824/41202 files, 3407351 reads, ETA: 24:30:29
All threads submitted - waiting for threads to terminate
Waiting for writer to terminate
Exception in thread "ForkJoinPool-5-worker-3" java.util.concurrent.RejectedExecutionException
	at java.base/java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2179)
	at java.base/java.util.concurrent.ForkJoinPool.externalSubmit(ForkJoinPool.java:2196)
	at java.base/java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2664)
	at com.google.common.util.concurrent.MoreExecutors$ListeningDecorator.execute(MoreExecutors.java:631)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:69)
	at com.rw.nanoporereadscanner.WorkerReadscanner$JobDoneCallBack.onSuccess(WorkerReadscanner.java:353)
	at com.rw.nanoporereadscanner.WorkerReadscanner$JobDoneCallBack.onSuccess(WorkerReadscanner.java:313)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Exception in thread "ForkJoinPool-5-worker-5" java.util.concurrent.RejectedExecutionException
	at java.base/java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2179)
	at java.base/java.util.concurrent.ForkJoinPool.externalSubmit(ForkJoinPool.java:2196)
	at java.base/java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2664)
	at com.google.common.util.concurrent.MoreExecutors$ListeningDecorator.execute(MoreExecutors.java:631)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:69)
	at com.rw.nanoporereadscanner.WorkerReadscanner$JobDoneCallBack.onSuccess(WorkerReadscanner.java:353)
	at com.rw.nanoporereadscanner.WorkerReadscanner$JobDoneCallBack.onSuccess(WorkerReadscanner.java:313)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Finished parsing - calculating barcodes and stats

=======  Scan Stats =======

All Reads	4,100,000		
Chimeric reads split	124,988	3.0 %	of All Reads
Multi Chimeric reads discarded n>3	863	.0 %	of All Reads
Reads after chimera split	4,239,523		
Reads from split chimeric	264,511	6.2 %	of Reads after chimera split
Passed (Adapter found)	3,413,594	80.5 %	of Reads after chimera split
Mean read length pA and Adapter found	913		
Mean read length pA and Adapter NOT found	897		
Passed forward	1,940,964	45.8 %	of Reads after chimera split
Passed reverse	1,472,630	34.7 %	of Reads after chimera split
Passed total, found TSO other end	1,470,787	43.1 %	of Passed (Adapter found)
PolyT found only at 5\'	1,491,477	35.2 %	of Reads after chimera split
PolyA found only at 3\'	1,957,936	46.2 %	of Reads after chimera split
PolyA not found	734,648	17.3 %	of Reads after chimera split
PolyT 5\' and PolyA at 3\'	29,499	.7 %	of Reads after chimera split
Adapter at 5\'(3\' for 5p barcoding)	1,472,630	34.7 %	of Reads after chimera split
Adapter at 3\'(5\' for 5p barcoding)	1,940,964	45.8 %	of Reads after chimera split
TSO at 5\'	88,846	2.1 %	of Reads after chimera split
TSO at 3\'	2,065,632	48.7 %	of Reads after chimera split
Read too short	25,100	.6 %	of Reads after chimera split
Adapter at 5\' and 3\'	10,214	.2 %	of Reads after chimera split
TSO at 5\' and 3\'	1,719	.0 %	of Reads after chimera split
TSO at 5\' and 3\' failed	573	.0 %	of Reads after chimera split
Barcode found	2,857,341	83.7 %	of Passed (Adapter found)
Barcode found no secondary at <= ED + 2	2,333,884	68.4 %	of Passed (Adapter found)
Barcode found ED= 0	2,469,570	86.4 %	of Barcode found
Barcode found ED= 1	387,771	13.6 %	of Barcode found
Barcode secondary match ED diff > 2	2,333,884	81.7 %	of Barcode found
Barcode secondary match ED diff 1	523,457	18.3 %	of Barcode found
Barcode offset from predicted pos=0	2,735,398	95.7 %	of Barcode found
Barcode offset from predicted pos=+/-1	82,404	2.9 %	of Barcode found
Barcode offset from predicted pos=+/-2	39,539	1.4 %	of Barcode found
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/scratch/smlab/jindalk/230411_longreads_iep_pilot/sil2/sicelore-2.1/Jar/lib/slf4j-reload4j-1.7.34.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
------------------------------
DONE -- Duration: 03:49:42.015
```

**Comment by RainerWaldmann** [comment]
In the first pass the software defines the used barcodes. It only uses high quality reads. It is normal that the read count printed is lower than the total number of reads.
The second pass threw an exception.  It did not complete and this is why the read count is low.
Typically each thread takes less than a minute to complete. In your case a thread took more than two hours to complete. One possible reason might be insufficient RAM.
How much RAM did you allocate ?

**Comment by jindalk** [comment]
Hi, I used 20 cores and 120G RAM. I'm running this on a compute cluster so I can certainly bump that up significantly if needed. Just not sure what is a good ballpark for resources. My run has 190 mil reads (180G bases).

**Comment by RainerWaldmann** [comment]
Hi,

One step that requires some RAM are the distance matrices used for UMI clustering. If you have cells that have a huge number of reads for a genomic region the memory requirement increases. It is not a fixed read count - RAM relation, it depends how those reads are distributed over the genome. 
I think you should give it a try with 400 G of RAM.
I am currently reducing the RAM requirement. I'll release an updated version soon.

Rainer
